// src/pages/admin/question/question_add.tsx
import React from 'react'
import BackCom from "../../../components/back";
import AddFormCom from "../../../components/admin/question/add_form";
import './question.css'

export default function () {
  return (
    <div className='admin-content'>
      <div className='admin-form'>
        <BackCom />
      </div>
      <div className='admin-list admin-center'>
        <AddFormCom />
      </div>
    </div>
  )
}

// web/src/pages/admin/question/question_add.vue
<template>
  <div class='question_add'>
    <AddForm />
  </div>
</template>

<script lang='ts'>
import { defineComponent } from 'vue';
import AddForm from '@/components/admin/question/add_form.vue'
export default defineComponent({
  setup() {},
  components: {
    AddForm
  }
});
</script>


<style scoped>
.question_add {
  display: flex;
  justify-content: center;
}
</style>
