// src/components/admin/menu.tsx
import React from "react";
import { Menu } from "antd";
import { AreaChartOutlined, UsergroupDeleteOutlined, TableOutlined, ContainerOutlined, BarsOutlined } from "@ant-design/icons";
import { Link } from "react-router-dom";
const { SubMenu } = Menu;

export default () => {
  return (
    <div style={{ maxWidth: "100%" }}>
      <div className="admin-logo">QN2QU-ADMIN</div>
      <Menu mode="inline" theme="dark">
        <Menu.Item key="ADMIN_QUESTION" icon={<BarsOutlined />}>
          <Link to="/admin/question">题目管理</Link>
        </Menu.Item>
        <Menu.Item key="ADMIN_PAPER" icon={<ContainerOutlined />}>
          <Link to="/admin/paper">套题管理</Link>
        </Menu.Item>
        <Menu.Item key="ADMIN_COMPETITION" icon={<TableOutlined />}>
          <Link to="/admin/competition">竞赛管理</Link>
        </Menu.Item>
        <SubMenu key="USER" icon={<AreaChartOutlined />} title="人员管理">
          <Menu.Item key="ADMIN_USER_AUTH" icon={<UsergroupDeleteOutlined />}>
            <Link to="/admin/user/auth">权限管理</Link>
          </Menu.Item>
          <Menu.Item key="ADMIN_USER_MANAGER" icon={<UsergroupDeleteOutlined />}>
            <Link to="/admin/user/manager">人员管理</Link>
          </Menu.Item>
        </SubMenu>
        <SubMenu key="STATUSTICS" icon={<AreaChartOutlined />} title="统计">
          <Menu.Item key="STATUSTICS_QUESTION">
            <Link to="/admin/statistics/question">题目统计</Link>
          </Menu.Item>
          <Menu.Item key="STATUSTICS_PAPER">
            <Link to="/admin/statistics/paper">套题统计</Link>
          </Menu.Item>
          <Menu.Item key="STATUSTICS_COMPETITION">
            <Link to="/admin/statistics/competition">竞赛统计</Link>
          </Menu.Item>
        </SubMenu>
        <Menu.Item key="ADMIN_SETTING" icon={<BarsOutlined />}>
          <Link to="/admin/setting">设置</Link>
        </Menu.Item>
      </Menu>
    </div>
  );
};

// src/components/admin/menu.vue
<template>
  <div class="menu">
    <div class="logo" />
    <a-menu theme="dark" v-model:selectedKeys="selectedKeys" mode="inline">
      <a-menu-item key="ADMIN_QUESTION">
        <BarsOutlined />
        <span>题目管理</span>
        <router-link to="/admin/question">题目管理</router-link>
      </a-menu-item>
      <a-menu-item key="ADMIN_PAPER">
        <ContainerOutlined />
        <span>套题管理</span>
        <router-link to="/admin/testpaper">套题管理</router-link>
      </a-menu-item>
      <a-menu-item key="ADMIN_COMPETITION">
        <TableOutlined />
        <span>竞赛管理</span>
        <router-link to="/admin/competition">竞赛管理</router-link>
      </a-menu-item>
      <a-sub-menu key="ADMIN_USER">
        <template #title>
          <span>
            <UsergroupDeleteOutlined />
            <span>人员管理</span>
          </span>
        </template>
        <a-menu-item key="ADMIN_USER_AUTH">
          <span>权限管理</span>
          <router-link to="/admin/user/auth">权限管理</router-link>
        </a-menu-item>
        <a-menu-item key="ADMIN_USER_manager">
          <span>人员管理</span>
          <router-link to="/admin/user/manager">人员管理</router-link>
        </a-menu-item>
      </a-sub-menu>
      <a-sub-menu key="ADMIN_STATISTICS">
        <template #title>
          <span>
            <AreaChartOutlined />
            <span>统计</span>
          </span>
        </template>
        <a-menu-item key="ADMIN_STATISTICS_QUESTION">
          <span>题目统计</span>
          <router-link to="/admin/statistics/question">题目统计</router-link>
        </a-menu-item>
        <a-menu-item key="ADMIN_CHART_PAPER">
          <span>套题统计</span>
          <router-link to="/admin/statistics/paper">套题统计</router-link>
        </a-menu-item>
        <a-menu-item key="ADMIN_CHART_COMPETITION">
          <span>竞赛统计</span>
          <router-link to="/admin/statistics/competition">竞赛统计</router-link>
        </a-menu-item>
      </a-sub-menu>
      <a-menu-item key="ADMIN_SETTING">
        <SettingOutlined />
        <span>设置</span>
        <router-link to="/admin/setting">设置</router-link>
      </a-menu-item>
    </a-menu>
  </div>
</template>

<script lang="ts">
import { BarsOutlined, SettingOutlined, ContainerOutlined, TableOutlined, UsergroupDeleteOutlined, AreaChartOutlined } from "@ant-design/icons-vue";
import { defineComponent, ref } from "vue";
export default defineComponent({
  components: {
    BarsOutlined,
    SettingOutlined,
    ContainerOutlined,
    TableOutlined,
    UsergroupDeleteOutlined,
    AreaChartOutlined,
  },
  setup() {
    const selectedKeys = ref<string[]>(["ADMIN_SETTING"]);
    return { selectedKeys };
  },
});
</script>

<style scoped>
.menu .logo {
  height: 60px;
  width: 200px;
  background-color: #001529;
}
</style>
